variables:
  HOSTS: "master:tj1-dba-garm-test02.kscn:3308,\
      slave:tj1-dba-garm-test01.kscn:3308"

before_script:
  - export GOPROXY="https://goproxy.cn/";

stages:
  - check
  - unittest
  - build
  - integrate_tests
  - e2e-test

code_check:
  stage: check
  script:
    - make check

unit_tests:
  stage: unittest
  image: micr.cloud.mioffice.cn/miflow-base/golang:1.16.6-centos7.3
  script:
    - ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime
    - ls -l /etc/localtime
    - make test

build_branch:
  stage: build
  script:
    - make


integrate_tests:
  stage: integrate_tests
  script:
    - echo "Start to build gaea"
    - make gaea
    - echo "start integrate tests"
    - sed -i "s/IT_USER/${IT_USER}/g" cmd/gaea/main_test.go
    - sed -i "s/IT_PASSWORD/${IT_PASSWORD}/g" cmd/gaea/main_test.go
    - echo "${IT_USER}:""${PASSWORD}"
    - cat cmd/gaea/main_test.go
    - nohup bin/gaea -config etc/gaea.ini &
    - sleep 10
    - make integrate_test
    - ps -ef | grep gaea | grep -v grep | awk '{print $2}' | xargs kill -9


e2e_test:
  stage: e2e-test
  script:
    - echo "e2e test"
