image: micr.cloud.mioffice.cn/dockerhub/library/golang:1.16.15

variables:
  HOSTS: "master:tj1-dba-garm-test02.kscn:3308,\
      slave:tj1-dba-garm-test01.kscn:3308"

cache:
  key: "$CI_COMMIT_REF_SLUG"
  paths:
    - bin/

before_script:
  - export GOPROXY="https://goproxy.cn/";
  - export GO111MODULE=on;

stages:
  - test
  - scan
  - check
  - unittest
  - build
  - e2e-test
  - pre-release
  - release

.fusion-cli: &fusion-cli
  image:
    name: cr.d.xiaomi.net/container/xiaomi_alpine_fusion_cli
  before_script:
    - fusion-cli config --access-key ${CD_AK} --secret-key ${CD_SK}

go_test:
  stage: test
  image: cr.d.xiaomi.net/miflow/golang:1.17-centos7.3 # 对应build镜像
  only:
    refs:
      - master # 对应线上分支
      - /^test.*$/
      - /^release.*$/
      - feat/test_sonar
  script:
    - go test -v ./... -coverprofile=coverage.out -short || true
  artifacts:
    paths:
      - coverage.out

sonar_scan:
  stage: scan
  only:
    refs:
      - master # 对应线上分支
      - /^test.*$/
      - /^release.*$/
      - feat/test_sonar
  dependencies:
    - go_test
  <<: *fusion-cli
  script:
    - fusion-cli sonar config --token $CI_SONAR_TOKEN
    - fusion-cli sonar scan --key=$CI_PROJECT_ID-$CI_PROJECT_NAME --ignore-quality-gate --sources . --report --
      -Dsonar.exclusions='**/vendor/**','**/*_test.go','**/tests/**'
      -Dsonar.test.exclusions='**/vendor/**','**/*_test.go','**/tests/**'
      -Dsonar.go.coverage.reportPaths='coverage.out'
      -Dsonar.branch.name=$CI_COMMIT_REF_NAME
      -Dsonar.projectVersion=$CI_COMMIT_SHORT_SHA
      -Dsonar.verbose

code_check:
  stage: check
  image: micr.cloud.mioffice.cn/dockerhub/library/golang:1.16.15
  script:
    - make check

unit_tests:
  stage: unittest
  image: micr.cloud.mioffice.cn/miflow-base/golang:1.16.6-centos7.3
  script:
    - ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime
    - ls -l /etc/localtime
    - make test
    - echo "sql parser test"
    - cd parser && make test

build_branch:
  stage: build
  script:
    - make build

e2e_test:
  stage: e2e-test
  image: micr.cloud.mioffice.cn/devdba/centos-mysql-golang:v1.0.2
  script:
    - make e2e-test

upload_fds:
  stage: pre-release
  only:
    - staging
  <<: *fusion-cli
  script:
    - DAY=`date +%Y-%m-%d`
    - fusion-cli fds --endpoint ${CD_FDS_ENDPOINT} copy bin/gaea fds://${CD_FDS_BUCKET}/${DAY}/gaea
    - fusion-cli fds --endpoint ${CD_FDS_ENDPOINT} copy bin/gaea-cc fds://${CD_FDS_BUCKET}/${DAY}/gaea-cc
    - fusion-cli fds --endpoint ${CD_FDS_ENDPOINT} copy etc/gaea_online.ini fds://${CD_FDS_BUCKET}/${DAY}/gaea.ini

release:
  stage: release
  <<: *fusion-cli
  only:
    - tags
  script:
    - fusion-cli fds --endpoint ${CD_FDS_ENDPOINT} copy bin/gaea fds://${CD_FDS_BUCKET}/${CI_COMMIT_TAG}/gaea
    - fusion-cli fds --endpoint ${CD_FDS_ENDPOINT} copy bin/gaea-cc fds://${CD_FDS_BUCKET}/${CI_COMMIT_TAG}/gaea-cc
    - fusion-cli fds --endpoint ${CD_FDS_ENDPOINT} copy etc/gaea_online.ini fds://${CD_FDS_BUCKET}/${CI_COMMIT_TAG}/gaea.ini

