image: micr.cloud.mioffice.cn/dockerhub/library/golang:1.16.15

variables:
  HOSTS: "master:tj1-dba-garm-test02.kscn:3308,\
      slave:tj1-dba-garm-test01.kscn:3308"

cache:
  key: "$CI_COMMIT_REF_SLUG"
  paths:
    - bin/

before_script:
  - export GOPROXY="https://goproxy.cn/";
  - export GO111MODULE=on;

stages:
  - check
  - unittest
  - build
  - integrate_tests
  - e2e-test
  - pre-release
  - release

.fusion-cli: &fusion-cli
  image:
    name: cr.d.xiaomi.net/container/xiaomi_alpine_fusion_cli
  before_script:
    - fusion-cli config --access-key ${CD_AK} --secret-key ${CD_SK}

code_check:
  stage: check
  image: micr.cloud.mioffice.cn/dockerhub/library/golang:1.16.15
  script:
    - make check

unit_tests:
  stage: unittest
  image: micr.cloud.mioffice.cn/miflow-base/golang:1.16.6-centos7.3
  script:
    - ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime
    - ls -l /etc/localtime
    - make test
    - echo "sql parser test"
    - cd parser && make test

build_branch:
  stage: build
  script:
    - make build

integrate_tests:
  stage: integrate_tests
  timeout: 1h
  script:
    - echo "Start to build gaea"
    - make gaea
    - echo "start integrate tests"
    - sed -i "s/IT_USER/${IT_USER}/g" cmd/gaea/main_test.go
    - sed -i "s/IT_PASSWORD/${IT_PASSWORD}/g" cmd/gaea/main_test.go
    - nohup bin/gaea -config etc/gaea.ini &
    - sleep 10
    - make integrate_test
    - ps -ef | grep gaea | grep -v grep | awk '{print $2}' | xargs kill -9

e2e_test:
  stage: e2e-test
  image: micr.cloud.mioffice.cn/devdba/centos-mysql-golang:v1.0.2
  script:
    - cp bin/gaea tests/e2e/cmd/
    - cp bin/gaea-cc tests/e2e/cmd/
    - ./hack/e2e.sh
    - ginkgo --v --progress --trace --flake-attempts=1 ./tests/e2e/

upload_fds:
  stage: pre-release
  only:
    - staging
  <<: *fusion-cli
  script:
    - DAY=`date +%Y-%m-%d`
    - fusion-cli fds --endpoint ${CD_FDS_ENDPOINT} copy bin/gaea fds://${CD_FDS_BUCKET}/${DAY}/gaea
    - fusion-cli fds --endpoint ${CD_FDS_ENDPOINT} copy bin/gaea-cc fds://${CD_FDS_BUCKET}/${DAY}/gaea-cc

release:
  stage: release
  <<: *fusion-cli
  only:
    - tags
  script:
    - fusion-cli fds --endpoint ${CD_FDS_ENDPOINT} copy bin/gaea fds://${CD_FDS_BUCKET}/${CI_COMMIT_TAG}/gaea
    - fusion-cli fds --endpoint ${CD_FDS_ENDPOINT} copy bin/gaea-cc fds://${CD_FDS_BUCKET}/${CI_COMMIT_TAG}/gaea-cc

