variables:
  HOSTS: "master:tj1-dba-garm-test02.kscn:3308,\
      slave:tj1-dba-garm-test01.kscn:3308"

before_script:
  - export GOPROXY="https://goproxy.cn/";

stages:
  - check
  - test
  - build
  - integrate_tests
  - e2e-test

code_check:
  stage: check
  script:
    - make check

unit_tests:
  stage: test
  script:
    - echo "unit test"

build_branch:
  stage: build
  script:
    - pwd


integrate_tests:
  stage: integrate_tests
  script:
    - echo "start integrate tests"
    - nohup bin/gaea -config etc/gaea.ini &
    - sleep 10
    - make integrate_test

e2e_test:
  stage: e2e-test
  script:
    - echo "e2e test"
