image: micr.cloud.mioffice.cn/dockerhub/library/golang:1.16.15

variables:
  HOSTS: "master:tj1-dba-garm-test02.kscn:3308,\
      slave:tj1-dba-garm-test01.kscn:3308"

cache:
  key: "$CI_COMMIT_REF_SLUG"
  paths:
    - bin/

before_script:
  - export GOPROXY="https://goproxy.cn/";
  - export GO111MODULE=on;

stages:
  - check
  - unittest
  - build
  - integrate_tests
  - e2e-test
  - pre-release
  - release

.fusion-cli: &fusion-cli
  image:
    name: cr.d.xiaomi.net/container/xiaomi_alpine_fusion_cli
  before_script:
    - fusion-cli config --access-key ${CD_AK} --secret-key ${CD_SK}

code_check:
  stage: check
  image: micr.cloud.mioffice.cn/dockerhub/library/golang:1.16.15
  script:
    - make check

unit_tests:
  stage: unittest
  image: micr.cloud.mioffice.cn/miflow-base/golang:1.16.6-centos7.3
  script:
    - ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime
    - ls -l /etc/localtime
    - make test
    - echo "sql parser test"
    - cd parser && make test

build_branch:
  stage: build
  script:
    - make build

e2e_test:
  stage: e2e-test
  image: micr.cloud.mioffice.cn/devdba/centos-mysql-golang:v1.0.2
  script:
    - cp bin/gaea tests/cmd/
    - cp bin/gaea-cc tests/cmd/
    - go install github.com/onsi/ginkgo/v2/ginkgo@v2.3.1
    - chmod +x ./hack/e2e.sh
    - ./hack/e2e.sh
    - ginkgo --v --progress --trace --flake-attempts=1 ./tests/e2e/

upload_fds:
  stage: pre-release
  only:
    - staging
  <<: *fusion-cli
  script:
    - DAY=`date +%Y-%m-%d`
    - fusion-cli fds --endpoint ${CD_FDS_ENDPOINT} copy bin/gaea fds://${CD_FDS_BUCKET}/${DAY}/gaea
    - fusion-cli fds --endpoint ${CD_FDS_ENDPOINT} copy bin/gaea-cc fds://${CD_FDS_BUCKET}/${DAY}/gaea-cc
    - fusion-cli fds --endpoint ${CD_FDS_ENDPOINT} copy etc/gaea_online.ini fds://${CD_FDS_BUCKET}/${DAY}/gaea.ini

release:
  stage: release
  <<: *fusion-cli
  only:
    - tags
  script:
    - fusion-cli fds --endpoint ${CD_FDS_ENDPOINT} copy bin/gaea fds://${CD_FDS_BUCKET}/${CI_COMMIT_TAG}/gaea
    - fusion-cli fds --endpoint ${CD_FDS_ENDPOINT} copy bin/gaea-cc fds://${CD_FDS_BUCKET}/${CI_COMMIT_TAG}/gaea-cc
    - fusion-cli fds --endpoint ${CD_FDS_ENDPOINT} copy etc/gaea_online.ini fds://${CD_FDS_BUCKET}/${CI_COMMIT_TAG}/gaea.ini

